language: node_js

node_js:
  - "5.1"

before_install:
  - sudo -v && wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main(install_dir='/usr/local')"

script:
  - gitbook build -v 2.6.7
  - gitbook pdf -v 2.6.7 . _book/guidelines.pdf
  - grunt deploy

env:
  global:
  - secure: "TBD"
